### PR TITLE
 feat(encoding/yaml): encoding yaml package based on gopkg.in/yaml.v2

### PR DESCRIPTION
**Pull request by mcuadros**
This PR depends on https://github.com/qri-io/starlib/pull/34

### CODE REVIEW

**Comment by b5** [comment]
This looks really great. Thanks so much for the contribution, and for taking time to follow the existing conventions in this repo @mcuadros. I'm out for the evening, but will make sure someone reviews this ASAP.

**Comment by mcuadros** [comment]
BTW will be great make a `test` package to avoid copy paste and using something like `testify` for the asserts.

Also I have a question how the README.md is generated, because in the case I did by hand.

**Comment by b5** [comment]
readme is generated with [outline](https://github.com/b5/outline), a nascant tool we made for this problem of documenting python in go code.

_totally_ agreed on a test package. We've avoided using assert-utils like testify because everyone argues over which one to use.

**Comment by mcuadros** [comment]
Well the people can argue, but you can do whatever you want :D, what is true that that if you change your mind, as we did at source{d} you can ending having `gocheck` and`testify`.

**Pull request merged**
